puts "\nUsage: todo [options] COMMAND\n\n"
puts "Commands:"
puts "  add TODO        Adds a todo"
puts "  delete NUM      Removes a todo"
puts "  done NUM        Completes a todo"
puts "  clear           Removes all todo"
puts "  list [FILTER]   Lists all active todos"
